### ISSUE TITLE
Dependencies in build 4 broken (lzma?)

### ISSUE THREAD

**Issue by epruesse** [conda-forge/fontconfig-feedstock#19]
The 2.12.1-4 package has broken library dependencies (on OSX, didn't check linux). I double checked this file: https://anaconda.org/conda-forge/fontconfig/2.12.1/download/osx-64/fontconfig-2.12.1-4.tar.bz2

Notably, with build 4, liblzma is required to link but not included with any of the packages included through the run dependency hierarchy. 

It may just require a rebuild.

Perhaps it would be useful to have `conda inspect linkages|objects` fail if any binaries are found to require libs that aren't in $PREFIX or /usr/lib or are in a "blacklist" (libz)?

```
# otool -L miniconda3/pkgs/fontconfig-2.12.1-4/lib/libfontconfig.1.dylib
pkgs/fontconfig-2.12.1-4/lib/libfontconfig.1.dylib:
	@rpath/libfontconfig.1.dylib (compatibility version 11.0.0, current version 11.2.0)
	@rpath/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.6.0)
	@rpath/libpng16.16.dylib (compatibility version 45.0.0, current version 45.0.0)
	@rpath/libxml2.2.dylib (compatibility version 12.0.0, current version 12.4.0)
	@rpath/libicui18n.58.dylib (compatibility version 58.0.0, current version 58.1.0)
	@rpath/libicuuc.58.dylib (compatibility version 58.0.0, current version 58.1.0)
	@rpath/libicudata.58.dylib (compatibility version 58.0.0, current version 58.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	@rpath/liblzma.5.dylib (compatibility version 8.0.0, current version 8.2.0)
	@rpath/libiconv.2.dylib (compatibility version 8.0.0, current version 8.1.0)

$ otool -L miniconda3/pkgs/fontconfig-2.12.1-3/lib/libfontconfig.1.dylib
miniconda3/pkgs/fontconfig-2.12.1-3/lib/libfontconfig.1.dylib:
	@rpath/libfontconfig.1.dylib (compatibility version 11.0.0, current version 11.2.0)
	@rpath/libfreetype.6.dylib (compatibility version 18.0.0, current version 18.4.0)
	@rpath/libxml2.2.dylib (compatibility version 12.0.0, current version 12.4.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libiconv.2.dylib (compatibility version 8.0.0, current version 8.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

**Comment by jakirkham** [comment]
It's probably linking to the copy of `xz` from `libxml2`. Interestingly this is a run time dependency, so I'm not sure why it doesn't get pulled in for you. More details about your environment would be helpful in understanding the cause.

That said, have dug in the build logs and verified that you are correct about `xz` being linked to. The fix should be simple. Feel free to submit a PR adding the dependency, with [proper pinning]( https://github.com/conda-forge/conda-forge.github.io/blob/f6d30624c65a615c596468d9fa8cbd61a3aa9d4b/scripts/pin_the_slow_way.py#L69 ), and adding a build number bump.

The checks are great ideas and people have discussed them before. If you have some code you would like to contribute along those lines, let's chat more about this.

**Comment by epruesse** [comment]
Turns out I had a defaults channel libxml2 installed, which wasn't pulling xz. Re-ordering the channels fixed it for me.

How does conda (policy) handle indirect dependencies, actually? Technically, fontconfig does not itself depend on xz, but even if a newer libxml2 package would no longer require it, the fontconfig binaries would still contain the requirement in the dll (at least the way my dlls look on osx). 

Also, are there plans to add some of the more complex features present in e.g. dpkg? Such as `provides`, `conflicts`, `breaks`, `suggests`, `recommends`, `enhances` or ways to require one of a set of packages (`libxml2  2.1.2* | libxml3 | libxml-ng` or so)?

**Comment by jakirkham** [comment]
> How does conda (policy) handle indirect dependencies, actually?

If the package is linking to them, we should add them as dependencies. That said, it is pretty easy to miss this sort of thing. So maybe we need some kind of tooling to explicitly check all dependencies are accounted for. Feel free to submit a PR to make `fontconfig` require this if you haven't already done so.

> Also, are there plans to add some of the more complex features present in e.g. dpkg? Such as provides, conflicts, breaks, suggests, recommends, enhances or ways to require one of a set of packages (libxml2 2.1.2* | libxml3 | libxml-ng or so)?

While interesting, these would be things to raise at the `conda-build` tracker. This is to ensure these land in front of the right audience so that they can implement support for them for future recipes. Once they exist, we can discuss how we want to use them here.

**Comment by epruesse** [comment]
>While interesting, these would be things to raise at the conda-build tracker

Done ;-) conda/conda-build#1935

**Comment by mingwandroid** [comment]
FWIW, the lzma/xz dependency here is not needed. It is brought in by `libtool` due to it appearing in the `libxml2.la` file.

Once/if you adopt my fixes to libtool:

https://github.com/AnacondaRecipes/libtool-feedstock/commit/3bb6cfa9a6bd247787ace39c6c5af56352865333#diff-ae18fe4e01e61a9862ceaf165003213a
https://github.com/AnacondaRecipes/libtool-feedstock/commit/fd7d98baae330a3f8d359af9f6cc7f24ae69ae6a#diff-ae18fe4e01e61a9862ceaf165003213a

.. and use our compiler + linker  flags and this [commit](https://github.com/AnacondaRecipes/fontconfig-feedstock/commit/6167e27cce56490662f7910e766c82f8501b31a0#diff-ae18fe4e01e61a9862ceaf165003213a) to regenerate fontconfig's libtool script (`-Wl,--as-needed`) this DSO will no longer be listed as `DT_NEEDED`.
